//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaharovaPractica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int idpayment { get; set; }
        public int idorder { get; set; }
        public decimal sum { get; set; }
        public System.DateTime dateofpayment { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
