//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaharovaPractica.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int idrecord { get; set; }
        public int idclient { get; set; }
        public int idemployee { get; set; }
        public int idservices { get; set; }
        public System.DateTime recorddate { get; set; }
        public System.TimeSpan recordtime { get; set; }
    
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
        public virtual service service { get; set; }
    }
}
